image: node:22

default:
  interruptible: true
  timeout: 1 minute

stages:
  - test
  - deploy

test:
  stage: test
  variables:
    VITE_GITHUB_OAUTH_CLIENT_ID: "********************"
    VITE_GITHUB_OAUTH_CLIENT_SECRET: "****************************************"
  script:
    - npm run test

pages:
  stage: deploy
  script:
    - npm run build
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    variables:
      - $CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME
