name = "shakespeare-iframe-proxy"
main = "worker.js"
compatibility_date = "2023-10-30"

# Development environment
[env.development]
vars = { ENVIRONMENT = "development" }

# Production environment
[env.production]
vars = { ENVIRONMENT = "production" }

# Optional: Add custom domains for production
# [env.production.routes]
# pattern = "your-domain.com/*"
# zone_name = "your-domain.com"